/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/residential_building.glb --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_61: THREE.Mesh
    Object_62: THREE.Mesh
    Object_63: THREE.Mesh
    Object_64: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_68: THREE.Mesh
    Object_69: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_73: THREE.Mesh
    Object_74: THREE.Mesh
    Object_75: THREE.Mesh
    Object_76: THREE.Mesh
    Object_77: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_109: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_113: THREE.Mesh
    Object_115: THREE.Mesh
    Object_117: THREE.Mesh
    Object_119: THREE.Mesh
    Object_120: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_126: THREE.Mesh
    Object_128: THREE.Mesh
    Object_130: THREE.Mesh
    Object_132: THREE.Mesh
    Object_134: THREE.Mesh
    Object_135: THREE.Mesh
    Object_137: THREE.Mesh
    Object_139: THREE.Mesh
  }
  materials: {
    ['m.StoneTile.001']: THREE.MeshStandardMaterial
    ['Plaster.001']: THREE.MeshStandardMaterial
    Plaster: THREE.MeshStandardMaterial
    Frame: THREE.MeshStandardMaterial
    ['m.StoneTile.002']: THREE.MeshStandardMaterial
    Darkk: THREE.MeshStandardMaterial
    ['m.GlassReal.002']: THREE.MeshStandardMaterial
    Roof: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/residential_building-compressed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials['m.StoneTile.001']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['m.StoneTile.001']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['m.StoneTile.001']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Plaster} />
      <mesh geometry={nodes.Object_17.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['m.StoneTile.002']} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.Darkk} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.Darkk} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.Frame} />
      <mesh geometry={nodes.Object_80.geometry} material={materials['m.GlassReal.002']} />
      <mesh geometry={nodes.Object_82.geometry} material={materials['m.GlassReal.002']} />
      <mesh geometry={nodes.Object_84.geometry} material={materials['m.GlassReal.002']} />
      <mesh geometry={nodes.Object_86.geometry} material={materials['m.GlassReal.002']} />
      <mesh geometry={nodes.Object_88.geometry} material={materials['m.GlassReal.002']} />
      <mesh geometry={nodes.Object_90.geometry} material={materials['m.GlassReal.002']} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.Darkk} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.Plaster} />
      <mesh geometry={nodes.Object_96.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_98.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_100.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_102.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_104.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_106.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_108.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_109.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_110.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_112.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_113.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_115.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_117.geometry} material={materials.Plaster} />
      <mesh geometry={nodes.Object_119.geometry} material={materials.Darkk} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.Roof} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.Darkk} />
      <mesh geometry={nodes.Object_124.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.Plaster} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.Plaster} />
      <mesh geometry={nodes.Object_130.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.Plaster} />
      <mesh geometry={nodes.Object_134.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_135.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_137.geometry} material={materials['Plaster.001']} />
      <mesh geometry={nodes.Object_139.geometry} material={materials['m.StoneTile.002']} />
    </group>
  )
}

useGLTF.preload('/residential_building-compressed.glb')
